# Generated by Django 5.2.2 on 2026-01-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('java', 'Java')], max_length=20)),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('options_en', models.JSONField()),
                ('options_ru', models.JSONField()),
                ('correct_option', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('middle', 'Middle')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectrecommendation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('roadmap', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('tasks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
