# Generated by Django 5.2.2 on 2026-01-12 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_testquestion_category_testresult_ai_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='category',
            field=models.CharField(choices=[('basics', '1. Основы и Типы данных'), ('logic', '2. Переменные и Логика'), ('arrays', '3. Списки и Коллекции'), ('functions', '4. Функции и Методы'), ('objects', '5. Объекты и Классы'), ('errors', '6. Обработка ошибок'), ('async', '7. Асинхронность'), ('apis', '8. Работа с API и Сетью'), ('patterns', '9. Архитектура и Паттерны'), ('final', '10. Финальное испытание')], default='basics', max_length=50),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('passed', 'Passed'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
