# Generated by Django 5.2.2 on 2026-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_alter_testquestion_category_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homework',
            name='correct_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
