# Generated by Django 5.2.2 on 2026-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_course_module_lesson_userlessonprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='practice_task',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='theory_content',
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(default='', help_text='Theory text or Task description (EN)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(default='', help_text='Theory text or Task description (RU)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Reference solution for AI hints'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='title_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Simple match checks'),
        ),
    ]
