# Generated by Django 5.2.2 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_lesson_practice_tasks_lesson_theory_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
