# Generated by Django 5.2.2 on 2026-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='track',
            field=models.CharField(choices=[('backend', 'Backend (Python)'), ('frontend', 'Frontend (HTML/CSS/JS)')], default='backend', max_length=20),
        ),
    ]
